name: dfunct
version: 0.0.6
author: Vizidrix <admin@vizidrix.com>
description: |-
  A functional library for Dart inspired by Haskell.
  Maybe monad and a bunch of typedefs for common scenarios.
homepage: https://github.com/Vizidrix/dfunct
documentation: https://github.com/Vizidrix/dfunct/tree/master/doc
dependencies:
  meta: '>=0.4.1'
dev_dependencies:
  unittest: '>=0.4.1'
  benchmark_harness: any
