name: dfunct
version: 0.0.2
author: Vizidrix <admin@vizidrix.com>
description: |-
  A functional library for Dart inspired by Haskell.
  Only has Maybe monad so far...
homepage: https://github.com/Vizidrix/dfunct
documentation: https://github.com/Vizidrix/dfunct/tree/master/doc
dependencies:
  unittest: 0.4.1
  meta: 0.4.1
